# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Manual Deploy (Spring Boot)

on:
  workflow_dispatch:   # ðŸ‘ˆ manual trigger only

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Stop application service
      run: |
        sudo systemctl stop usermanagement || true

    - name: Deploy jar to /opt
      run: |
        sudo mkdir -p /opt/usermanagement
        sudo cp target/usermanagement-0.0.1-SNAPSHOT.jar /opt/usermanagement/app.jar

    - name: Start application service
      run: |
        sudo systemctl start usermanagement

    - name: Check service status
      run: |
        sudo systemctl status usermanagement --no-pager

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
